services:
  reverse_proxy_app:
    build:
      context: ./reverse_proxy
      dockerfile: Dockerfile
    image: lua-reverse-proxy:latest
    container_name: reverse_proxy_container
    ports:
      - 80:80 # localport:dockerport
  redis_app:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: redis-img:latest
    container_name: redis_container
    volumes:
      - ./initial_data_redis.txt:/tmp/initial_data_redis.txt
    ports:
      - 6379:6379 # localport:dockerport
  # redis_appに初期パスワー投入するためのクライアント
  redis_client:
    image: redis:latest
    command: >
      /bin/bash -c 'cat /tmp/initial_data_redis.txt | redis-cli -h 127.0.0.1 -p 6379 SET user "password"'
    depends_on:
      - redis_app
