services:
  reverse_proxy_app:
    build:
      context: ./reverse_proxy
      dockerfile: Dockerfile
    image: lua-reverse-proxy:latest
    container_name: reverse_proxy_container
    ports:
      - 80:80 # localport:dockerport

