# Dev Containerではこちらが優先される。
services:
  reverse_proxy_app:
    build:
      target: devcontainer
      context: ./reverse_proxy
      dockerfile: Dockerfile
    image: reverse_proxy_devcontainer:latest
    container_name: reverse_proxy-devcontainer-container
    volumes:
      - ./reverse_proxy/:/usr/local/openresty/reverse_proxy
      # NOTE: install-pkg.shをコンテナに追加する
      - ./.devcontainer:/usr/local/openresty/.devcontainer
      # NOTE: ./install-pkg.shでインストールしたパッケージをキャッシュするためのディレクトリ
      - ./.devcontainer/cache:/cache 

  redis_app:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: redis-img:latest
    container_name: redis_container
    ports:
      - 6379:6379 # localport:dockerport
  # NOTE: redis_appに初期データを投入するために一時的なコンテナを立ち上げている。
  redis_client:
    image: redis:latest
    volumes:
      - ./redis/initial_data_redis.sh:/tmp/initial_data_redis.sh
    command: >
      /bin/bash -c 'source /tmp/initial_data_redis.sh'
    depends_on:
      - redis_app

