# Dev Containerではこちらが優先される。
services:
  reverse_proxy_app:
    build:
      target: devcontainer
      context: ./reverse_proxy
      dockerfile: Dockerfile
    image: reverse_proxy_devcontainer:latest
    container_name: reverse_proxy-devcontainer-container
    volumes:
      - ./reverse_proxy/:/usr/local/openresty/reverse_proxy
      # NOTE: サブディレクトリであるreverse_proxy/をマウントしているため，install-pkg.shをコンテナに追加する必要がある。
      - ./.devcontainer:/usr/local/openresty/.devcontainer

  redis_app:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: redis-img:latest
    container_name: redis_container
    ports:
      - 6379:6379 # localport:dockerport
